# Register a new sensor
POST http://localhost:3000/sensors 
Content-Type: application/json

{
    "sensor_id": "aqi-001",
    "type": "air_quality",
    "location": { "lat": 40.7128, "lng": -79.0060 },
    "description": "Subway air quality monitor"
}

###

# Retrieve a list of all registered sensors
GET http://localhost:3000/sensors 


###

# Get details for a specific sensor by its IDGet details for a specific sensor by its ID
GET http://localhost:3000/sensors/aqi-001
